###
GET http://localhost:4000/user

###
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "username": "vanhien2001",
    "password": "vanhien735"
}

###
POST http://localhost:4000/user/register
Content-Type: application/json

{
    "firstname": "Duy Khang",
    "lastname": "Phùng",
    "username": "duykhangpdk",
    "email": "duykhangpdk0701@gmail.com",
    "password": "123"
}

###
PUT http://localhost:4000/category/617e4a1404c48f208fa9dc13
Content-Type: application/json

{
    "name": "Laptop1"
}

###

DELETE  http://localhost:4000/category/617e4b1a01199071e2b17d75
